// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using VoylokTrade.Models;

namespace VoylokTrade.Migrations
{
    [DbContext(typeof(VoylokTradeDbContext))]
    [Migration("20180305141226_EditedGoodModelForActualPrices")]
    partial class EditedGoodModelForActualPrices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VoylokTrade.Models.Good", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Manufacturer");

                    b.Property<string>("Name");

                    b.Property<int?>("PriceMarkupInPercent");

                    b.Property<double?>("PricePerGood");

                    b.Property<int?>("TareVolume");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<double?>("Weight");

                    b.Property<int?>("WeightType");

                    b.HasKey("Id");

                    b.ToTable("Goods");
                });
#pragma warning restore 612, 618
        }
    }
}
